---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sonarqube
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  strategy: {}
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - image: 10.10.150.105/myapp/sonarqube:7.6-community
        name: sonarqube
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_USERNAME
          value: "postgres"
        - name: SONARQUBE_JDBC_PASSWORD
          value: "dangerous"
        - name: SONARQUBE_JDBC_URL
          value: "jdbc:postgresql://mysql:3306/sonardb?useUnicode=true&characterEncoding=utf8&useSSL=false"
        livenessProbe:
          httpGet:
            path: /sessions/new
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /sessions/new
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 6
        resources:
          limits:
            cpu: 1000m
            memory: 1048Mi
          requests:
            cpu: 1000m
            memory: 1048Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  type: NodePort
  ports:
    - name: sonarqube
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: sonarqube
