FROM nginx:1.25.1-alpine-slim
#FROM --platform=$TARGETPLATFORM nginx:1.25.1-alpine-slim
LABEL MAINTAINER Wan Jie <jie.wan@daocloud.io>

ENV TIMEZONE="Asia/Shanghai" \
    BUILD_DEPS="tzdata \
                sudo \
                nano \
                bash \
                bind-tools"
RUN apk update && \
    apk add --no-cache ${BUILD_DEPS}                        && \
    cp -rfv  /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && \
    echo ${TIMEZONE} > /etc/timezone                        && \
    apk del tzdata                                          && \
    apk add --no-cache curl ca-certificates && \
    touch /etc/ca-certificates.conf && \
    rm -rf /var/cache/apk/*
COPY dist /usr/share/nginx/html
COPY dist/default.conf /etc/nginx/conf.d/default.conf
COPY Dockerfile /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
